server:
  port: 8888

spring:
  application:
    name: pharmacy-config

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo/
        health:
          enabled: true

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
    env:
      enabled: false
    info:
      enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
